<?php

use App\Models\User;
use Carbon\Carbon;
use Illuminate\Database\Seeder;

class UserTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('users')->insert([
            array(
                'name'         => 'Cong NV',
                'slug'         => 'cong-nv',
                'email'        => 'congnv@gmail.com',
                'password'     => bcrypt('123456'),
                'gender'       => User::GENDER_FEMALE,
                'is_leader'    => 1,
                'bio'          => 'Technology is just a tool. In terms of getting the kids working together and motivating them, the teacher is the most important.',
                'major'        => User::DEVELOPER_MAJOR,
                'grade'        => 'K10',
                'birthday'     => '1991-10-10',
                'address'      => 'Ha Noi',
                'avatar_image' => 'mr cong.jpg',
                'created_at'   => Carbon::now(),
                'updated_at'   => Carbon::now(),
            ),
            array(
                'name'         => 'Binh DC',
                'slug'         => 'binh-dc',
                'email'        => 'binhdc@gmail.com',
                'password'     => bcrypt('123456'),
                'gender'       => User::GENDER_FEMALE,
                'bio'          => 'The number one benefit of information technology is that it empowers people to do what they want to do. It lets people be creative. It lets people be productive. It lets people learn things they didnot think they could learn before, and so in a sense it is all about potential',
                'is_leader'    => 0,
                'major'        => User::DEVELOPER_MAJOR,
                'grade'        => 'K12',
                'birthday'     => '1992-10-10',
                'address'      => 'Ha Noi',
                'avatar_image' => 'mr Binh.jpg',
                'created_at'   => Carbon::now(),
                'updated_at'   => Carbon::now(),
            ),
            array(
                'name'         => 'Dung',
                'slug'         => 'dung',
                'email'        => 'dung@gmail.com',
                'password'     => bcrypt('123456'),
                'gender'       => User::GENDER_FEMALE,
                'bio'          => 'It has become appallingly obvious that our technology has exceeded our humanity.',
                'is_leader'    => 0,
                'major'        => User::DEVELOPER_MAJOR,
                'grade'        => 'K13',
                'birthday'     => '1996-10-10',
                'address'      => 'Ha Noi',
                'avatar_image' => 'mr Dung.jpg',
                'created_at'   => Carbon::now(),
                'updated_at'   => Carbon::now(),
            ),
            array(
                'name'         => 'Hai Gemini',
                'slug'         => 'hai-gemini',
                'email'        => 'gemini.wind285@gmail.com',
                'gender'       => 1,
                'password'     => bcrypt('123456'),
                'bio'          => 'The first rule of any technology used in a business is that automation applied to an efficient operation will magnify the efficiency. The second is that automation applied to an inefficient operation will magnify the inefficiency.',
                'is_leader'    => 0,
                'major'        => User::DEVELOPER_MAJOR,
                'grade'        => 'K13',
                'birthday'     => '1995-05-28',
                'address'      => 'Ha Noi',
                'avatar_image' => 'mr Hai.jpg',
                'created_at'   => Carbon::now(),
                'updated_at'   => Carbon::now(),
            ),
            array(
                'name'         => 'Nam Kominam',
                'slug'         => 'nam-kominam',
                'email'        => 'kominam2511@gmail.com',
                'gender'       => User::GENDER_FEMALE,
                'password'     => bcrypt('123456'),
                'bio'          => 'Technology is a gift of God. After the gift of life it is perhaps the greatest of Gods gifts. It is the mother of civilizations, of arts and of sciences',
                'is_leader'    => 0,
                'major'        => User::DEVELOPER_MAJOR,
                'grade'        => 'K13',
                'birthday'     => '1995-11-25',
                'address'      => 'Ha Noi',
                'avatar_image' => 'mr Nam.jpg',
                'created_at'   => Carbon::now(),
                'updated_at'   => Carbon::now(),
            ),
            array(
                'name'         => 'Nhan',
                'slug'         => 'nhan',
                'email'        => 'nhan@gmail.com',
                'gender'       => User::GENDER_FEMALE,
                'password'     => bcrypt('123456'),
                'bio'          => 'One machine can do the work of fifty ordinary men. No machine can do the work of one extraordinary man.',
                'is_leader'    => 0,
                'major'        => User::DEVELOPER_MAJOR,
                'grade'        => 'K13',
                'birthday'     => '1996-10-10',
                'address'      => 'Ha Noi',
                'avatar_image' => 'mr Nhan.jpg',
                'created_at'   => Carbon::now(),
                'updated_at'   => Carbon::now(),
            ),
            array(
                'name'         => 'Quan',
                'slug'         => 'quan',
                'email'        => 'quan@gmail.com',
                'gender'       => User::GENDER_FEMALE,
                'password'     => bcrypt('123456'),
                'bio'          => 'The first rule of any technology used in a business is that automation applied to an efficient operation will magnify the efficiency. The second is that automation applied to an inefficient operation will magnify the inefficiency.',
                'is_leader'    => 0,
                'major'        => User::DEVELOPER_MAJOR,
                'grade'        => 'K14',
                'birthday'     => '1996-10-10',
                'address'      => 'Ha Noi',
                'avatar_image' => 'mr Quan.jpg',
                'created_at'   => Carbon::now(),
                'updated_at'   => Carbon::now(),
            ),
            array(
                'name'       => 'Anh Uno',
                'slug'       => 'anh-uno',
                'email'      => 'rubik.hanu@gmail.com',
                'gender'     => User::GENDER_MALE,
                'password'   => bcrypt('123456'),
                'bio'        => 'Technology is a gift of God. After the gift of life it is perhaps the greatest of Gods gifts. It is the mother of civilizations, of arts and of sciences.',
                'is_leader'  => 0,
                'major'      => User::DEVELOPER_MAJOR,
                'grade'      => 'K13',
                'birthday'   => '1991-10-10',
                'address'    => 'Hung Yen',
                'avatar_image'    => 'mrs Anh.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'name'         => 'Huyen',
                'slug'         => 'huyen',
                'email'        => 'huyen@gmail.com',
                'gender'       => User::GENDER_MALE,
                'password'     => bcrypt('123456'),
                'bio'          => 'Our technological powers increase, but the side effects and potential hazards also escalate.',
                'is_leader'    => 0,
                'major'        => User::DEVELOPER_MAJOR,
                'grade'        => 'K13',
                'birthday'     => '1996-10-10',
                'address'      => 'Hung Yen',
                'avatar_image' => 'mrs Huyen.jpg',
                'created_at'   => Carbon::now(),
                'updated_at'   => Carbon::now(),
            ),
            array(
                'name'         => 'Phuong',
                'slug'         => 'phuong',
                'email'        => 'phuong@gmail.com',
                'gender'       => User::GENDER_MALE,
                'password'     => bcrypt('123456'),
                'bio'          => 'Technology gives us power, but it does not and cannot tell us how to use that power. Thanks to technology, we can instantly communicate across the world, but it still doesnt help us know what to say.',
                'major'        => User::DEVELOPER_MAJOR,
                'is_leader'    => 0,
                'grade'        => 'K13',
                'birthday'     => '1996-10-10',
                'address'      => 'Ha Noi',
                'avatar_image' => 'mrs Phuong.jpg',
                'created_at'   => Carbon::now(),
                'updated_at'   => Carbon::now(),
            ),
            array(
                'name'         => 'Thanh ',
                'slug'         => 'thanh',
                'email'        => 'thanh@gmail.com',
                'gender'       => User::GENDER_FEMALE,
                'password'     => bcrypt('123456'),
                'bio'          => 'We re still in the first minutes of the first day of the Internet revolution',
                'is_leader'    => 0,
                'major'        => User::DEVELOPER_MAJOR,
                'grade'        => 'K13',
                'birthday'     => '1996-10-10',
                'address'      => 'Ha Noi',
                'avatar_image' => 'mr Thanh.jpg',
                'created_at'   => Carbon::now(),
                'updated_at'   => Carbon::now(),
            ),
            array(
                'name'         => 'Thao ',
                'slug'         => 'thao',
                'email'        => 'thao@gmail.com',
                'gender'       => User::GENDER_FEMALE,
                'password'     => bcrypt('123456'),
                'bio'          => 'Technology... is a queer thing. It brings you great gifts with one hand, and it stabs you in the back with the other.',
                'is_leader'    => 0,
                'major'        => User::DESIGNER_MAJOR,
                'grade'        => 'K13',
                'birthday'     => '1996-10-10',
                'address'      => 'Ha Noi',
                'avatar_image' => 'ms Thao.jpg',
                'created_at'   => Carbon::now(),
                'updated_at'   => Carbon::now(),
            ),
            array(
                'name'         => 'Thuong ',
                'slug'         => 'thuong',
                'email'        => 'thuong@gmail.com',
                'gender'       => User::GENDER_FEMALE,
                'password'     => bcrypt('123456'),
                'bio'          => 'Everybody gets so much information all day long that they lose their common sense.',
                'is_leader'    => 0,
                'major'        => User::DESIGNER_MAJOR,
                'grade'        => 'K13',
                'birthday'     => '1996-10-10',
                'address'      => 'Ha Noi',
                'avatar_image' => 'ms Thuong.jpg',
                'created_at'   => Carbon::now(),
                'updated_at'   => Carbon::now(),
            ),
        ]);
    }
}
