<?php
return [
    'hanusoft_give'      => 'Hanusoft will give you a chance to',
    'learn'              => 'learn',
    'practice'           => 'practice',
    'experience'         => 'experience',
    'join_with_us'       => 'Join with us ',
    'invite'             => ' You are passionate about the technology? You want to create the application, e-commerce sites or interested games by yourself? And you are wondering how to be able to raise, train your own skills at the same time have the opportunity to pursue other passions .So do not hesitate any longer, join with us, Hanusoft will accompany you!',
    'who_we_are_explain' => 'Hanusoft was built in 2006 based on the idea of ​​sharing knowledge to improve their skills and experience in the IT field. For those who are not have knowledge about information technology, programming a job is always sublime, mysterious and it makes people fed up with this boring. In fact, even with the new students to coding how to learn the code,understand it and writing it clearly is always a difficult challenge. Hence, Hanusoft desire to create an academic playground for all students who have enthusiasts of Information Technology, at the same time encourages and promotes student learning, doing scientific research and work as teams in a collaborative environment. And together we make programming become an intersting inspiration not boring as what we normally know about it. The enthusiasm of the teachers in the department and members have experienced had promoted the club became an academic discussion with good organization. Hanusoft currently playing a useful and practical for those who love programming, especially Java and PHP programming of IT students of Hanoi University.',
    'history_2016'       => 'In 2016, we continue to finish FIT portal project also recieve other project to gain mỏe experiences. the iportance thing is organize new recruiment to have new Hanusoft generations  .',
    'history_2013'       => ' Though many year of development Hanusoft also have interupt period for one or other reasons. with many mature generations. It is not a milestone until 2013 Hanusoft have briliants development as ever. There are many ex-members from F1 and F2 generations had accompany with the newest to take part in the semina with other from KOSEN group to share knowledge',
    'history_2007'       => 'First we have to mention our most millestone in long time development period. It is 2007 became the foundation step to establish Hanusoft as the official club of Hanoi university about IT. Though still as the new club but we had attract many student want to join. Our F1 generations was the one who had biggest passionate with IT and wish to learn more also raise skills. They was successful and gain many achievements as Hanusoft member',
];
